services:
  elasticsearch:
    image: bitnami/elasticsearch:latest
    container_name: elasticsearch
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - elastic
  
  kibana:
    image: bitnami/kibana:latest
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      KIBANA_ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge